### ISSUE TITLE
Possibillity to reduce Time to Scan certain Temp-censors

### ISSUE THREAD

**Issue by pos-ei-don** [crycode-de/ioBroker.ds18b20#102]
I have a lot of Temp Sensors!
There are Times, when I'd need certain Sensors to scan more frequent.
For Example, after switching on the circulation-pump to stop it when a certain temperature is arrived.
I do not need any values when the pump is switched off.

In Summer, i need other Temeratures as in winter.
When the Pool is in use, i need the current temperatures from the pipes. in winter, one value a day is enough.

There are many examples.
My Wife cannot go to the iobroker and deacticate some Sensors, while activationg some others.

Do you see any possibility to scan certain sensors for a short period of time more often?
Writing its name into an object, or anything like this?

best regards,
Philipp

**Comment by crycode-de** [comment]
Hi Philipp,

to do so, you may set the query interval for the affected sensors to `0` to disable the automatic readout.
Then (or in addition to the automatic read) you can write the ID of the sensor you wish to read into the state `ds18b20.0.actions.readNow`. (see [docs](https://github.com/crycode-de/ioBroker.ds18b20/blob/master/docs/en/ds18b20.md#actions))

Alternatively you may use the `sendTo` action in scripts to send the read command directly to the adapter instance. (see [docs](https://github.com/crycode-de/ioBroker.ds18b20/blob/master/docs/en/ds18b20.md#using-in-scripts))
Example:
```js
sendTo('ds18b20.0', 'readNow', '28-0000077ba131');
```

Each time you want to read the sensor, you write the ID into the state or send it directly to the adapter.


For the switch between summer and winter, you may use the option to enable or disable single sensors. Or you use two adapter instances - one for summer and one for winter - and start/stop them as required.
