### ISSUE TITLE
Auflösung

### ISSUE THREAD

**Issue by stefantaust** [crycode-de/ioBroker.ds18b20#106]
Ich bekomme Werte in 0,5 grad Schritten geliefert. Kann man es feiner auch noch machen? 0,1 wäre super

**Comment by crycode-de** [comment]
Die ausgelesene Genauigkeit hat nichts mit dem Adapter zu tun. Der Adapter ließt nur das, was vom Kernel bereitgestellt wird.

Es gibt verschiedene DS18*20 Sensoren:
* Die DS18**S**20 haben eine Auflösung von 9 Bit (0,5°C).
* Die DS18**B**20 haben standardmäßig 12 Bit, können aber auf 9 bis 12 Bit konfiguriert werden.
