### ISSUE TITLE
20 Sensoren

### ISSUE THREAD

**Issue by stefantaust** [crycode-de/ioBroker.ds18b20#108]
Hallo, ich würde gerne 20 Sensoren anschließen. Habe es aufgeteilt auf 4 Gpios. Es is noch kein Sensor angeschlossen, aber in Iobroker bekomme ich scho was rein. Kann ich überhaupt 4 verschiedene Gpios als 1 wire nutzen? 
Auf jeden Strang habe ich den Pullup.

![image](https://user-images.githubusercontent.com/58149673/207711531-4b1a5597-4de7-4fb7-921e-3b9c69f19efd.jpeg)
![image](https://user-images.githubusercontent.com/58149673/207711560-41101655-1f83-4a22-820e-fbb18cee5257.jpeg)
![image](https://user-images.githubusercontent.com/58149673/207711583-9a3b4f29-cd23-4c19-86a8-93690c83910d.jpeg)

**Comment by crycode-de** [comment]
Hi, ja das geht mit mehreren GPIOs. Du siehst ja schon, dass die _w1_bus_master1_ bis _4_ vorhanden sind. Jeder Master ist quasi ein GPIO.
Seltsam, dass da schon 3 Geräte am _w1_bus_master4_ erkannt werden. Hast du da noch irgendwas anderes dran?
Ebenso die drei "not found." im Adapter...

Kannst du mal posten, was in den Dateien steht?
`/sys/bus/w1/devices/w1_bus_master1/w1_master_slaves`
`/sys/bus/w1/devices/w1_bus_master2/w1_master_slaves`
`/sys/bus/w1/devices/w1_bus_master3/w1_master_slaves`
`/sys/bus/w1/devices/w1_bus_master4/w1_master_slaves`

Du kannst auch mal im Kernel-Log schauen, ob da irgendwas zum 1-wire Bus geloggt wird mittels `dmesg | grep w1`.

**Comment by stefantaust** [comment]
Danke für Deine Rückmeldung. Hier die Daten ![image](https://user-images.githubusercontent.com/58149673/207957009-5c8b1b9b-9414-43fb-a1a1-729d302ac0b8.jpeg)

Von dem log sind es mehrere Seiten 
![image](https://user-images.githubusercontent.com/58149673/207957104-dc12727f-f4d4-4942-b297-bde74d41714c.jpeg)

**Comment by crycode-de** [comment]
Ja, versuch mal einen anderen GPIO. Irgendwas scheint da auf der Leitung zu stören, wodurch er denkt da wären Geräte dran, die es aber gar nicht gibt.

**Comment by stefantaust** [comment]
Hab jetzt mal nur Gpio4 in der config eingetragen und keine Sensoren angeschlossen. Hab aber trotzdem Einträge.
 ![image](https://user-images.githubusercontent.com/58149673/208291268-4f8cfd0d-ac89-4dbf-89da-34888334fb61.jpeg)

![image](https://user-images.githubusercontent.com/58149673/208291277-294eb709-db94-4439-82a3-07e48222d28b.jpeg)

**Comment by crycode-de** [comment]
Hast du den Pullup-Widerstand zwischen 3,3V und dem GPIO schon dran?
Wenn nicht, dann könnte das die erkannten "Geräte" erklären, da ein offener Eingang ohne Pullup o.ä. sehr störanfällig ist.

**Comment by stefantaust** [comment]
Ja, pullup ist dran. Der Eingang ist nicht offen. Die Adressen wechseln auch immer und sind verschieden 
![image](https://user-images.githubusercontent.com/58149673/208296170-dcec1fc5-fd59-4690-808f-3d2061dfe900.jpeg)

**Comment by crycode-de** [comment]
> Die Adressen wechseln auch immer und sind verschieden

Genau dieses Verhalten kommt, wenn der Eingang offen (nichts angeschlossen) ist.
Hast du vielleicht den falschen Pin am GPIO Header benutzt?
GPIO4 wäre physikalisch Pin 7. Siehe https://de.pinout.xyz/pinout/pin7_gpio4#

Ansonsten schließ doch mal einen Sensor an und schau was dann passiert.
