### ISSUE TITLE
Remote Verbindung zu entfernten Raspberry

### ISSUE THREAD

**Issue by ChR-iSz** [crycode-de/ioBroker.ds18b20#11]
Hallo Peter,

gibt es eine Möglichkeit auf einem entfernten Raspberry im Heimnetz diese Sensoren auszulesen.
Eventuell bräuchten wir eine Daemon, auf dem Zielgerät ?

-- Christian

**Comment by crycode-de** [comment]
Hallo Christian,
ich denke der richtige (ioBroker konforme) Ansatz ist hier, auf dem entfernten Raspi einen ioBroker Slave zu installieren und auf diesem eine Instanz des Adapters einzurichten.

**Comment by ChR-iSz** [comment]
Hallo Peter,

danke für die schnelle Antwort.
Okay, das ist mir dann doch zu viel Aufwand. Der remote rpi ist leider nur ein rpi-1b. Denke der wird mit iOBroker ein wenig überfordert.
Ich versuche mal einen Workaround für mich, indem ich die entfernten ds1820 Folders auf dem ioBroker Server einmounte, und entsprechende Symlinks nach /sys/bus/w1/devices/* lege. Vielleicht klappt das ja schon.

Vielen dank für die Rückantwort.

-- Christian

**Comment by crycode-de** [comment]
Der Aufwand ist eigentlich recht gering und ein ioBroker Slave läuft wunderbar auf dem Raspi 1B.
Ich habe auf einem Raspi 1B einen Slave mit 2 Adaptern (JavaScript und Radiohead) laufen.

Alternativ könnte man noch ein kleines Node.js Script schreiben, welches die Sensoren ausließt und den Wert dann z.B. mittels SimpleAPI oder MQTT an ioBroker schickt.

**Comment by ChR-iSz** [comment]
Danke Peter,

mit dem mounten hat es wunderbar geklappt. Du hast ja sogar schon den Path zu den sys Verzeichnis konfigurierbar gemacht. Konnte den Perfekt auf /mnt/sys.... ändern. Läuft soweit alles!

Danke für Deine Unterstützung!

-- Christian

**Comment by crycode-de** [comment]
Danke für die Info. Dann kann ich das ja mal mit in die Doku aufnehmen. :)

**Comment by crycode-de** [comment]
Kannst du mir vielleicht noch eine paar Infos dazu geben, was du jetzt wie genau gemountet hast? Danke schon mal! :)

**Comment by ChR-iSz** [comment]
Hallo Peter,

selbstverständlich.

**Remote-Raspi:**
`apt-get install samba-server`

In der `/etc/samba/smb.conf` folgendes an Ende hinzugefügt:

[ds1820]  
path = /sys/devices/w1_bus_master1  
comment = FBH Temperatur Sensoren.  
available = yes  
browseable = yes  
guest ok = yes  
writeable = no  
force user = root  
force group = root  


**IoBroker-Raspi**

`apt-get install smb-client`

In der `/etc/fstab` folgenden Eintrag hinzugefügt:
`//{IP-ADRESSE-REMOTE-RPI}/ds1820 /mnt/ds1820 cifs defaults,vers=1.0 0 0`

Verzeichnis anlegen:
`mkdir /mnt/ds1820`

Mounten
`mount -a`

Dann in IoBroker bei Deinem Plugin den Pfad `/mnt/ds1820` eingetragen.

**Comment by os25** [comment]
Hallo Peter,
habe auf dem 2. Pi Samba installiert, leider fehlen mir noch ein paar Kenntnisse.
Ich bekomme folgende Meldung
pi@garten:~ $ sudo systemctl restart samba
Failed to restart samba.service: Unit samba.service not found.
Vielleicht kannst Du mir helfen.

--Olaf

**Comment by crycode-de** [comment]
@os25 Der Serivce heißt `smbd` und nicht `samba`.
`sudo systemctl restart smbd` sollte funktionieren. Ich werde das gleich noch in der Doku anpassen.

**Comment by os25** [comment]
Danke für die schnelle Antwort,

habe auf iobroker folgende Befehle ausgeführt und verbindet sich scheinbar mit 2.PI
pi@iobroker:~ $ sudo mkdir -p /mnt/remote-ds1820
pi@iobroker:~ $ sudo mount /mnt/remote-ds1820
Password for root@//192.168.178.120/ds1820:  ********
pi@iobroker:~ $ 

Ordner /mnt/remote-ds1820 ist leer

beim suchen von weiteren Sensoren im iobroker fehlt scheinbar noch der richtige Pfad

Error: ENOENT: no such file or directory, open '/mnt/remote-ds1820/192.168.178.120/sys/devies/w1_bus_master1/w1_master_slaves'

danke für Info

**Comment by ChR-iSz** [comment]
Zeig mal die samba config vom 2.PI, wo du Deine Freigabe eingetragen hast. Samba server danach restartet auf dem 2.PI ?

**Comment by crycode-de** [comment]
@os25 Da passt dann noch was mit deinem Mount und der Adapterconfig nicht.

Für den Mount muss in der Datei `/etc/fstab` folgender Eintrag gemacht werden: (Unter der Annahme, dass 192.168.178.120 dein Remote Pi ist)
```
//192.168.178.120/ds1820 /mnt/remote-ds1820 cifs defaults,vers=1.0 0 0
```

Außerdem musst di in der Adapterconfig den Systempfad `/mnt/remote-ds1820` angeben.

**Comment by os25** [comment]
Samba config 2.PI


[ds1820]
path = /sys/devices/w1_bus_master1
comment = DS1820 Temperature sensors
available = yes
browseable = yes
guest ok = yes
writeable = no
force user = root
force group = root


Und adapterconfig auf  /mnt/remote-ds1820 geändert

**Comment by os25** [comment]
Ok 
Es hat geklappt
Danke

**Comment by LupinIII** [comment]
Das Freigeben funktioniert so nicht, da der Adapter das Unterverzeichnis `w1_bus_master1` lesen will (die Freigabe IST dieses Verzeichnis). Wie oben:
Error: ENOENT: no such file or directory, open '/mnt/remote-ds1820/w1_bus_master1/w1_master_slaves'

Das ganze `/sys/devices` Verzeichnis (in dem sich `w1_bus_master1` befindet) möchte ich mit root-Rechten aber auch nicht freigeben (aus Prinzip, auch wenn's nur der raspi ist). 

Ich habe daher ein Verzeichnis in `/srv` (ich denke, dort passt's am besten hin) 
```mkdir -p /srv/1wire```
und dort einen Symlink angelegt
```ln -s /sys/devices/w1_bus_master1/```

Die Samba-Share ist dann für `/srv/1wire`. Damit Symlinks in der Share funktionieren, muss man aber noch das in der smb.conf in den entsprechenden Abschnitten hinzufügen:
```
[global]
unix extensions = no
....

[ds1820]
follow symlinks = yes
wide links = yes
....
```

Damit finde ich jetzt zumindest die am Raspi angeschlossenen Sensoren übers Netzwerk, Temperatur sehe ich aber noch keine.
Für die Instanz ist "Connected to ds18b20" gleich "false"

**Comment by crycode-de** [comment]
Ich arbeite aktuell an einer Lösung bei der die Netzwerkfreigen dann komplett entfallen.

Mit v1.4.x wird es möglich sein, Remote-Systeme direkt per TCP Sockets über einen kleinen Service auf z.B. einen entfernten Raspi einzubinden.

**Comment by crycode-de** [comment]
Die Version **1.4.0** ist ab sofort auf NPM und ab morgen im latest Repo verfügbar.
Damit wird nun die Einbindung von entfernten Sensoren direkt im Adapter über den eigenen _Remote Client_ unterstützt. ([siehe Doku](https://github.com/crycode-de/ioBroker.ds18b20/blob/master/docs/de/ds18b20.md))
Somit sind jetzt die Umwege über Samba etc. nicht mehr notwendig. :-)
