### ISSUE TITLE
Pfad wird nicht erkannt

### ISSUE THREAD

**Issue by monnypython** [crycode-de/ioBroker.ds18b20#21]
Hi,

Ich habe bereits viele ds18b20 über das owfs-plugin eingebunden, mir gelingt es aber nicht in diesem Plugin.
Die sensoren sind am raspberry über owfs bzw. in /mnt/1wire eingebunden. Gebe ich den Pfad im Plugin ein werden aber keine Sensoren gefunden. Komisch ist, das ich eine Fehlermeldung mit einem anderen, als den von mir definierten Pfad erhalte?!

Was mache ich falsch? Wie gesagt, die Sensoren und die Verbindung in io-broker funktionieren sonst einwandfrei.

![Screenshot_3](https://user-images.githubusercontent.com/42573701/105530137-a9bf0100-5ce7-11eb-9bd4-7bf698f076a7.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/42573701/105530141-aa579780-5ce7-11eb-9077-64109861f25f.jpg)

**Comment by crycode-de** [comment]
Hi, sorry für die späte Antwort.

Bei der Suche nach Sensoren schaut der Adapter in der Datei `<Pfad>/w1_bus_master1/w1_master_slaves` nach, welche Geräte vom System erkannt wurden. Wenn es diese Datei nicht gibt, dann kommt der Fehler.

Wie genau hast du die Sensoren auf dem System eingebunden?

**Comment by crycode-de** [comment]
Ich arbeite aktuell an einer Lösung bei der die Dateifreigaben dann komplett entfallen.

Mit v1.4.x wird es möglich sein, Remote-Systeme direkt per TCP Sockets über einen kleinen Service auf z.B. einen entfernten Raspi einzubinden.

**Comment by crycode-de** [comment]
Die Version **1.4.0** ist ab sofort auf NPM und ab morgen im latest Repo verfügbar.
Damit wird nun die Einbindung von entfernten Sensoren direkt im Adapter über den eigenen _Remote Client_ unterstützt. ([siehe Doku](https://github.com/crycode-de/ioBroker.ds18b20/blob/master/docs/de/ds18b20.md))
Somit sind jetzt die Umwege über Samba etc. nicht mehr notwendig. :-)
