### ISSUE TITLE
Beschreibung Hardware Aufbau

### ISSUE THREAD

**Issue by thePhilipp** [crycode-de/ioBroker.ds18b20#4]
Moin Peter,

sehr geil, genau der Adapter den ich genau jetzt brauch. Ich habe vor, meine Heizungssteuerung über ioBroker zu realisieren. Ein Teil dieser Steuerung sollten jede Menge Sensoren an den Vor-und Rückläufen sein. Eigentlich sollten alle Sensoren an einem Nodemcu angebunden sein und per MQTT an ioBroker senden. Aber ich tue mich sehr schwer die passende Software in der arduinoIDE zu erstellen. 
Ein Raspberry soll aber sowieso mit in den Heizungsraum. Dieser wird dann die Ventile der Heizkreise schalten. Und jetzt mit deinem Adapter kann kann ich ja die Sensoren direkt anbinden. 
Hammer!
Hast du eine kurze Beschreibung zur Hand wie ich die Sensoren am Raspberry anschließe? Also welcher PIN, eventuell notwendiger pull up oder pull down Widerstand? 
Muss ich die Sensoren auf Linuxebene noch irgendwie einbinden? Also irgend welche Treiber oder so installieren?
Also auf jeden Fall schon einmal danke für den Adapter und danke für eventuell weitere Tips!

Gruß Philipp

**Comment by crycode-de** [comment]
Hallo Philipp,
danke für das positive Feedback. :-)

Ich habe die Doku um diesen Punkt erweitert: [DS18B20 am Raspberry Pi](https://github.com/crycode-de/ioBroker.ds18b20/blob/master/docs/de/ds18b20.md#ds18b20-am-raspberry-pi)

**Comment by thePhilipp** [comment]
Perfekt! Genau das was noch gefehlt hat. 

Danke und Gruß
