### ISSUE TITLE
(303046) Error reading sensor 28-0000073bbd98: Error: No response from remote system

### ISSUE THREAD

**Issue by tobintax** [crycode-de/ioBroker.ds18b20#40]
First of all: Thanks for the cool adapter!

I tried to get it running, but I get reading errors like 

"(303046) Error reading sensor 28-0000073bbd98: Error: No response from remote system" 

for all of my sensors: 

ds18b20.0 | 2021-04-18 23:32:28.915 | warn | (303046) Error reading sensor 28-0000073bbd98: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:32:28.915 | warn | (303046) Error reading sensor 28-0000073bbbf8: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:32:28.915 | warn | (303046) Error reading sensor 28-0316720d70ff: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:32:28.915 | warn | (303046) Error reading sensor 28-041670ea34ff: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:32:28.914 | warn | (303046) Error reading sensor 28-041670e7e1ff: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:32:28.912 | warn | (303046) Error reading sensor 28-051671a87bff: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:32:28.912 | warn | (303046) Error reading sensor 28-0316721457ff: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:31:28.915 | warn | (303046) Error reading sensor 28-0000073bbd98: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:31:28.915 | warn | (303046) Error reading sensor 28-0000073bbbf8: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:31:28.915 | warn | (303046) Error reading sensor 28-0316720d70ff: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:31:28.915 | warn | (303046) Error reading sensor 28-041670ea34ff: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:31:28.914 | warn | (303046) Error reading sensor 28-041670e7e1ff: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:31:28.912 | warn | (303046) Error reading sensor 28-051671a87bff: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:31:28.911 | warn | (303046) Error reading sensor 28-0316721457ff: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:30:28.914 | warn | (303046) Error reading sensor 28-0000073bbd98: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:30:28.914 | warn | (303046) Error reading sensor 28-0000073bbbf8: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:30:28.914 | warn | (303046) Error reading sensor 28-0316720d70ff: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:30:28.914 | warn | (303046) Error reading sensor 28-041670ea34ff: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:30:28.914 | warn | (303046) Error reading sensor 28-041670e7e1ff: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:30:28.913 | warn | (303046) Error reading sensor 28-051671a87bff: Error: No response from remote system
ds18b20.0 | 2021-04-18 23:30:28.910 | warn | (303046) Error reading sensor 28-0316721457ff: Error: No response from remote system

I'm using the adapter version 1.4.0. 

node --version
v10.24.1
Linux 5.10.27+

I'm able to read out all of the sensors with my python script without any problem. 
Any suggestions to get this running?

**Comment by crycode-de** [comment]
According to the error message, you are using the adapter with the remote client. Right?

The error message indicates, that the request has been send to the remote client but the client did not respond.

Please check the log output of the remote client.
Additionally you may enable the debug log output for the remote client by removing the `#` in front of `DEBUG=1` in the `.env` file of the remote client.

**Comment by tobintax** [comment]
Right, I'm using the remote client. 
I enabled debug logging, here is the output: 

_node ds18b20-remote-client.js
- ioBroker.ds18b20 remote client -
[Debug] read DEBUG=1 from .env file
[Debug] systemId heizungspi
[Debug] adapterPort 1820
[Debug] adapterHost 192.168.3.153
[Debug] adapterKey <Buffer 16 06 20 8d 01 6b dd 46 2f 6f a0 65 e7 36 d6 3a f7 83 5e b8 51 44 6c 11 b6 57 2b 9a 8f 2b d1 1f>
[Debug] w1DevicesPath /sys/bus/w1/devices
[Info] Connecting to 192.168.3.153:1820 ...
[Info] Connected with adapter
[Debug] message from adapter: { cmd: 'clientInfo', protocolVersion: 1 }
[Info] Sending client info to the adapter
[Debug] send to adapter: { cmd: 'clientInfo', protocolVersion: 1, systemId: 'heizungspi' }
[Debug] message from adapter: { cmd: 'read', ts: 1618831449492, address: '28-0316721457ff' }
[Debug] message from adapter: { cmd: 'read', ts: 1618831449493, address: '28-041670e7e1ff' }
[Debug] Read from file /sys/bus/w1/devices/28-0316721457ff/w1_slave: 50 05 4b 46 7f ff 0c 10 1c : crc=1c YES
50 05 4b 46 7f ff 0c 10 1c t=85000

[Debug] send to adapter: { cmd: 'read',
  address: '28-0316721457ff',
  ts: 1618831449492,
  raw:
   '50 05 4b 46 7f ff 0c 10 1c : crc=1c YES\n50 05 4b 46 7f ff 0c 10 1c t=85000\n' }
[Debug] Read from file /sys/bus/w1/devices/28-041670e7e1ff/w1_slave: 83 02 4b 46 7f ff 0c 10 e5 : crc=e5 YES
83 02 4b 46 7f ff 0c 10 e5 t=40187

[Debug] send to adapter: { cmd: 'read',
  address: '28-041670e7e1ff',
  ts: 1618831449493,
  raw:
   '83 02 4b 46 7f ff 0c 10 e5 : crc=e5 YES\n83 02 4b 46 7f ff 0c 10 e5 t=40187\n' }
[Debug] message from adapter: { cmd: 'read', ts: 1618831449493, address: '28-041670ea34ff' }
[Debug] message from adapter: { cmd: 'read', ts: 1618831449493, address: '28-0316720d70ff' }
[Debug] Read from file /sys/bus/w1/devices/28-041670ea34ff/w1_slave: 02 03 4b 46 7f ff 0c 10 09 : crc=09 YES
02 03 4b 46 7f ff 0c 10 09 t=48125

[Debug] send to adapter: { cmd: 'read',
  address: '28-041670ea34ff',
  ts: 1618831449493,
  raw:
   '02 03 4b 46 7f ff 0c 10 09 : crc=09 YES\n02 03 4b 46 7f ff 0c 10 09 t=48125\n' }
[Debug] Read from file /sys/bus/w1/devices/28-0316720d70ff/w1_slave: 01 02 4b 46 7f ff 0c 10 f1 : crc=f1 YES
01 02 4b 46 7f ff 0c 10 f1 t=32062

[Debug] send to adapter: { cmd: 'read',
  address: '28-0316720d70ff',
  ts: 1618831449493,
  raw:
   '01 02 4b 46 7f ff 0c 10 f1 : crc=f1 YES\n01 02 4b 46 7f ff 0c 10 f1 t=32062\n' }
[Debug] message from adapter: { cmd: 'read', ts: 1618831449493, address: '28-0000073bbbf8' }
[Debug] message from adapter: { cmd: 'read', ts: 1618831449493, address: '28-0000073bbd98' }
[Debug] Read from file /sys/bus/w1/devices/28-0000073bbbf8/w1_slave: a6 00 4b 46 7f ff 0a 10 cb : crc=cb YES
a6 00 4b 46 7f ff 0a 10 cb t=10375

[Debug] send to adapter: { cmd: 'read',
  address: '28-0000073bbbf8',
  ts: 1618831449493,
  raw:
   'a6 00 4b 46 7f ff 0a 10 cb : crc=cb YES\na6 00 4b 46 7f ff 0a 10 cb t=10375\n' }
[Debug] Read from file /sys/bus/w1/devices/28-0000073bbd98/w1_slave: 95 03 4b 46 7f ff 0b 10 71 : crc=71 YES
95 03 4b 46 7f ff 0b 10 71 t=57312

[Debug] send to adapter: { cmd: 'read',
  address: '28-0000073bbd98',
  ts: 1618831449493,
  raw:
   '95 03 4b 46 7f ff 0b 10 71 : crc=71 YES\n95 03 4b 46 7f ff 0b 10 71 t=57312\n' }_

**Comment by tobintax** [comment]
And here is the adapter output: 


ds18b20.0 | 2021-04-19 13:31:22.492 | warn | (326346) Error reading sensor 28-0000073bbd98: Error: No response from remote system
-- | -- | -- | --
ds18b20.0 | 2021-04-19 13:31:22.492 | warn | (326346) Error reading sensor 28-0000073bbbf8: Error: No response from remote system
ds18b20.0 | 2021-04-19 13:31:22.492 | warn | (326346) Error reading sensor 28-0316720d70ff: Error: No response from remote system
ds18b20.0 | 2021-04-19 13:31:22.492 | warn | (326346) Error reading sensor 28-041670ea34ff: Error: No response from remote system
ds18b20.0 | 2021-04-19 13:31:18.515 | debug | (326346) error state of sensor 28-041670e7e1ff changed to false
ds18b20.0 | 2021-04-19 13:31:18.514 | debug | (326346) got value 40.13 from sensor 28-041670e7e1ff
ds18b20.0 | 2021-04-19 13:31:18.513 | debug | (326346) data from remote ::ffff:192.168.3.189:49764: {"cmd":"read","address":"28-041670e7e1ff","ts":1618831877490,"raw":"82 02 4b 46 7f ff 0c 10 a6 : crc=a6 YES\n82 02 4b 46 7f ff 0c 10 a6 t=40125\n"
ds18b20.0 | 2021-04-19 13:31:18.488 | debug | (326346) got value null from sensor 28-0316721457ff
ds18b20.0 | 2021-04-19 13:31:18.487 | warn | (326346) Error reading sensor 28-0316721457ff: Error: No temperature read
ds18b20.0 | 2021-04-19 13:31:18.487 | debug | (326346) data from remote ::ffff:192.168.3.189:49764: {"cmd":"read","address":"28-0316721457ff","ts":1618831877490,"raw":"50 05 4b 46 7f ff 0c 10 1c : crc=1c YES\n50 05 4b 46 7f ff 0c 10 1c t=85000\n"
ds18b20.0 | 2021-04-19 13:30:35.987 | info | (326346) Remote system heizungspi connected from ::ffff:192.168.3.189
ds18b20.0 | 2021-04-19 13:30:35.987 | debug | (326346) data from remote ::ffff:192.168.3.189:49764: {"cmd":"clientInfo","protocolVersion":1,"systemId":"heizungspi"}
ds18b20.0 | 2021-04-19 13:30:35.855 | debug | (326346) socket connect ::ffff:192.168.3.189:49764
ds18b20.0 | 2021-04-19 13:30:31.002 | info | (326346) Remote system heizungspi (::ffff:192.168.3.189:49762) disconnected
ds18b20.0 | 2021-04-19 13:30:31.001 | debug | (326346) socket closed ::ffff:192.168.3.189:49762
ds18b20.0 | 2021-04-19 13:30:27.537 | info | (326346) Remote system heizungspi connected from ::ffff:192.168.3.189
ds18b20.0 | 2021-04-19 13:30:27.537 | debug | (326346) data from remote ::ffff:192.168.3.189:49762: {"cmd":"clientInfo","protocolVersion":1,"systemId":"heizungspi"}
ds18b20.0 | 2021-04-19 13:30:27.400 | debug | (326346) socket connect ::ffff:192.168.3.189:49762
ds18b20.0 | 2021-04-19 13:30:20.822 | debug | (326346) system.adapter.admin.0: logging true
ds18b20.0 | 2021-04-19 13:30:17.491 | warn | (326346) Error reading sensor 28-0000073bbd98: Error: Remote system heizungspi is not connected.
ds18b20.0 | 2021-04-19 13:30:17.491 | warn | (326346) Error reading sensor 28-0000073bbbf8: Error: Remote system heizungspi is not connected.
ds18b20.0 | 2021-04-19 13:30:17.491 | warn | (326346) Error reading sensor 28-0316720d70ff: Error: Remote system heizungspi is not connected.
ds18b20.0 | 2021-04-19 13:30:17.491 | warn | (326346) Error reading sensor 28-041670ea34ff: Error: Remote system heizungspi is not connected.
ds18b20.0 | 2021-04-19 13:30:17.491 | warn | (326346) Error reading sensor 28-041670e7e1ff: Error: Remote system heizungspi is not connected.
ds18b20.0 | 2021-04-19 13:30:17.491 | warn | (326346) Error reading sensor 28-0316721457ff: Error: Remote system heizungspi is not connected.
ds18b20.0 | 2021-04-19 13:30:17.491 | debug | (326346) loaded 6 sensors
ds18b20.0 | 2021-04-19 13:30:17.472 | info | (326346) Remote sensor server is listening on port 1820
ds18b20.0 | 2021-04-19 13:30:17.464 | info | (326346) starting. Version 1.4.0 in /opt/iobroker/node_modules/iobroker.ds18b20, node: v12.22.0, js-controller: 3.2.16
ds18b20.0 | 2021-04-19 13:30:17.416 | debug | (326346) Plugin sentry Initialize Plugin (enabled=true)
ds18b20.0 | 2021-04-19 13:30:17.344 | debug | (326346) statesDB connected
ds18b20.0 | 2021-04-19 13:30:17.344 | debug | (326346) States connected to redis: 127.0.0.1:9000
ds18b20.0 | 2021-04-19 13:30:17.341 | debug | (326346) States create User PubSub Client
ds18b20.0 | 2021-04-19 13:30:17.340 | debug | (326346) States create System PubSub Client
ds18b20.0 | 2021-04-19 13:30:17.337 | debug | (326346) Redis States: Use Redis connection: 127.0.0.1:9000
ds18b20.0 | 2021-04-19 13:30:17.337 | debug | (326346) objectDB connected
ds18b20.0 | 2021-04-19 13:30:17.335 | debug | (326346) Objects connected to redis: 127.0.0.1:9001
ds18b20.0 | 2021-04-19 13:30:17.326 | debug | (326346) Objects client initialize lua scripts
ds18b20.0 | 2021-04-19 13:30:17.326 | debug | (326346) Objects create User PubSub Client
ds18b20.0 | 2021-04-19 13:30:17.326 | debug | (326346) Objects create System PubSub Client
ds18b20.0 | 2021-04-19 13:30:17.325 | debug | (326346) Objects client ready ... initialize now
ds18b20.0 | 2021-04-19 13:30:17.309 | debug | (326346) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.ubuntu-iobroker | 2021-04-19 13:30:17.110 | info | instance system.adapter.ds18b20.0 started with pid 326346

**Comment by crycode-de** [comment]
Thank you for the information.
Seams like there is a race condition when using multiple remote sensors. I'll take a look at it.

**Comment by crycode-de** [comment]
This bug is fixed in v1.4.1 which is now available on NPM and will be in the latest repository tomorrow.

Please let me know, if you run into any other issues.

**Comment by tobintax** [comment]
Hi, doesn't look good: 


- ioBroker.ds18b20 remote client -
[Debug] read DEBUG=1 from .env file
[Debug] systemId heizungspi
[Debug] adapterPort 1820
[Debug] adapterHost 192.168.3.153
[Debug] adapterKey <Buffer 16 06 20 8d 01 6b dd 46 2f 6f a0 65 e7 36 d6 3a f7 83 5e b8 51 44 6c 11 b6 57 2b 9a 8f 2b d1 1f>
[Debug] w1DevicesPath /sys/bus/w1/devices
[Info] Connecting to 192.168.3.153:1820 ...
[Info] Connected with adapter
[Debug] message from adapter: { cmd: 'clientInfo', protocolVersion: 1 }
[Info] Sending client info to the adapter
[Debug] send to adapter: { cmd: 'clientInfo', protocolVersion: 1, systemId: 'heizungspi' }
[Debug] message from adapter: { cmd: 'read', ts: 1619029882464, address: '28-0316721457ff' }
[Debug] message from adapter: { cmd: 'read', ts: 1619029882465, address: '28-041670e7e1ff' }
[Debug] Read from file /sys/bus/w1/devices/28-0316721457ff/w1_slave: 50 05 4b 46 7f ff 0c 10 1c : crc=1c YES
50 05 4b 46 7f ff 0c 10 1c t=85000

[Debug] send to adapter: { cmd: 'read',
  address: '28-0316721457ff',
  ts: 1619029882464,
  raw:
   '50 05 4b 46 7f ff 0c 10 1c : crc=1c YES\n50 05 4b 46 7f ff 0c 10 1c t=85000\n' }
[Debug] Read from file /sys/bus/w1/devices/28-041670e7e1ff/w1_slave: 54 02 4b 46 7f ff 0c 10 ba : crc=ba YES
54 02 4b 46 7f ff 0c 10 ba t=37250

[Debug] send to adapter: { cmd: 'read',
  address: '28-041670e7e1ff',
  ts: 1619029882465,
  raw:
   '54 02 4b 46 7f ff 0c 10 ba : crc=ba YES\n54 02 4b 46 7f ff 0c 10 ba t=37250\n' }
[Debug] message from adapter: { cmd: 'read', ts: 1619029882466, address: '28-041670ea34ff' }
[Debug] message from adapter: { cmd: 'read', ts: 1619029882466, address: '28-0316720d70ff' }
[Debug] Read from file /sys/bus/w1/devices/28-041670ea34ff/w1_slave: f9 02 4b 46 7f ff 0c 10 fc : crc=fc YES
f9 02 4b 46 7f ff 0c 10 fc t=47562

[Debug] send to adapter: { cmd: 'read',
  address: '28-041670ea34ff',
  ts: 1619029882466,
  raw:
   'f9 02 4b 46 7f ff 0c 10 fc : crc=fc YES\nf9 02 4b 46 7f ff 0c 10 fc t=47562\n' }
[Debug] Read from file /sys/bus/w1/devices/28-0316720d70ff/w1_slave: e4 01 4b 46 7f ff 0c 10 93 : crc=93 YES
e4 01 4b 46 7f ff 0c 10 93 t=30250

[Debug] send to adapter: { cmd: 'read',
  address: '28-0316720d70ff',
  ts: 1619029882466,
  raw:
   'e4 01 4b 46 7f ff 0c 10 93 : crc=93 YES\ne4 01 4b 46 7f ff 0c 10 93 t=30250\n' }


Here is the adapter log: 


ds18b20.0 | 2021-04-21 20:32:42.260 | info | (22467) Remote system heizungspi (::ffff:192.168.3.189:43566) disconnected
-- | -- | -- | --
ds18b20.0 | 2021-04-21 20:32:42.260 | debug | (22467) socket closed ::ffff:192.168.3.189:43566
ds18b20.0 | 2021-04-21 20:32:27.467 | warn | (22467) Error reading sensor 28-0000073bbd98: Error: No response from remote system heizungspi
ds18b20.0 | 2021-04-21 20:32:27.466 | warn | (22467) Error reading sensor 28-0000073bbbf8: Error: No response from remote system heizungspi
ds18b20.0 | 2021-04-21 20:32:27.466 | warn | (22467) Error reading sensor 28-0316720d70ff: Error: No response from remote system heizungspi
ds18b20.0 | 2021-04-21 20:32:27.466 | warn | (22467) Error reading sensor 28-041670ea34ff: Error: No response from remote system heizungspi
ds18b20.0 | 2021-04-21 20:32:27.466 | warn | (22467) Error reading sensor 28-041670e7e1ff: Error: No response from remote system heizungspi
ds18b20.0 | 2021-04-21 20:32:27.466 | warn | (22467) Error reading sensor 28-0316721457ff: Error: No response from remote system heizungspi
ds18b20.0 | 2021-04-21 20:32:23.443 | debug | (22467) data from remote ::ffff:192.168.3.189:43566: {"cmd":"read","address":"28-0316720d70ff","ts":1619029882466,"raw":"e4 01 4b 46 7f ff 0c 10 93 : crc=93 YES\ne4 01 4b 46 7f ff 0c 10 93 t=30250\n"}
ds18b20.0 | 2021-04-21 20:32:23.405 | debug | (22467) data from remote ::ffff:192.168.3.189:43566: {"cmd":"read","address":"28-041670ea34ff","ts":1619029882466,"raw":"f9 02 4b 46 7f ff 0c 10 fc : crc=fc YES\nf9 02 4b 46 7f ff 0c 10 fc t=47562\n"}
ds18b20.0 | 2021-04-21 20:31:27.467 | warn | (22467) Error reading sensor 28-0000073bbd98: Error: No response from remote system heizungspi
ds18b20.0 | 2021-04-21 20:31:27.466 | warn | (22467) Error reading sensor 28-0000073bbbf8: Error: No response from remote system heizungspi
ds18b20.0 | 2021-04-21 20:31:27.466 | warn | (22467) Error reading sensor 28-0316720d70ff: Error: No response from remote system heizungspi
ds18b20.0 | 2021-04-21 20:31:27.466 | warn | (22467) Error reading sensor 28-041670ea34ff: Error: No response from remote system heizungspi
ds18b20.0 | 2021-04-21 20:31:23.480 | debug | (22467) error state of sensor 28-041670e7e1ff changed to false
ds18b20.0 | 2021-04-21 20:31:23.478 | debug | (22467) got value 37.25 from sensor 28-041670e7e1ff
ds18b20.0 | 2021-04-21 20:31:23.477 | debug | (22467) data from remote ::ffff:192.168.3.189:43566: {"cmd":"read","address":"28-041670e7e1ff","ts":1619029882465,"raw":"54 02 4b 46 7f ff 0c 10 ba : crc=ba YES\n54 02 4b 46 7f ff 0c 10 ba t=37250\n"}
ds18b20.0 | 2021-04-21 20:31:23.411 | debug | (22467) got value null from sensor 28-0316721457ff
ds18b20.0 | 2021-04-21 20:31:23.411 | warn | (22467) Error reading sensor 28-0316721457ff: Error: No temperature read
ds18b20.0 | 2021-04-21 20:31:23.410 | debug | (22467) data from remote ::ffff:192.168.3.189:43566: {"cmd":"read","address":"28-0316721457ff","ts":1619029882464,"raw":"50 05 4b 46 7f ff 0c 10 1c : crc=1c YES\n50 05 4b 46 7f ff 0c 10 1c t=85000\n"}
ds18b20.0 | 2021-04-21 20:31:09.316 | info | (22467) Remote system heizungspi connected from ::ffff:192.168.3.189

**Comment by tobintax** [comment]
And here is the Adapter Version: Version 1.4.1 in /opt/iobroker/node_modules/iobroker.ds18b20, node: v12.22.1, js-controller: 3.2.16

**Comment by crycode-de** [comment]
Did you reinstall the remote client?
Sorry forgot to mention that this is necessary.

You just need to run the `wget -O remote-client-setup.js http://...` and node `node remote-client-setup.js` commands inside your existing remote client installation.

**Comment by tobintax** [comment]
Thanks for the info and sorry, I missed that. After reinstalling the remote client it seems to work. Thanks for fixing it with like super pursuit mode :) Nochmals besten Dank!
