### ISSUE TITLE
Where are sensor objects created?

### ISSUE THREAD

**Issue by Apollon77** [crycode-de/ioBroker.ds18b20#5]
Hi,

I was doing some review and can not find the place where objects for the sensors are created. I only see setState ... DidI miss something or are objects not created? Then this is broken and needs to be fixed.

Thank you

Ingo

**Comment by Apollon77** [comment]
Ahhhh ... ok I found it now ...it is done in Admin https://github.com/crycode-de/ioBroker.ds18b20/blob/master/admin/index_m.html#L36 ... is it made sure that existing objects are not tried to be recreated that way? Because then extendObject or such would be better. If this is made sure I did not say anything and you can close ;-)

**Comment by crycode-de** [comment]
Hi Ingo,

when an object is changed (e.g. the name is updated) `setObject` will be emitted with the whole updated object like described here: https://github.com/crycode-de/ioBroker.ds18b20/blob/master/admin/index_m.html#L364
Will then the existing object be recreated or updated? So far I thought it will be updated.
Is it better to use `extendObject` to update existing objects?

Regards
Peter

**Comment by Apollon77** [comment]
No, setObject is a "hard rewrite". Beginning in js.controller 2.2 there is handling in to preserve some custom fields - from my knowledge this was planned also before but never really working :-( So people loose e.g history activation.

The best way would be a getObjects - set/extendObject approach

**Comment by crycode-de** [comment]
Ah ok, thank you for the information and review!
I'll change this in the next days. (and also in my other adapters, where I used the same logic)

**Comment by Apollon77** [comment]
Cool, thank you!

**Comment by crycode-de** [comment]
Fixed in v1.1.3
