### ISSUE TITLE
Feature Request: Disable a configured Sensor

### ISSUE THREAD

**Issue by Videonisse** [crycode-de/ioBroker.ds18b20#89]
Currently, when a configured sensor temporarily is removed from the 1Wire bus, it produces after each query a warning in the log. If possible, I suggest that each configured sensor can be disabled from the Adapter config page to avoid those messages.

Today I need to delete the sensor and add it again when it should be used. The disadvantage of this is that next time I need to configure the settings for "Factor" and "Decimals" again as well as enable the settings for History Adapter when used.

It would be much better just to click "Disable" to suppress warnings and "park" the sensor until it should be used again.

Is it possible to implement this feature?

**Comment by Videonisse** [comment]
Yes, of course, it solves the issue! Thanks for this Tip!

**Comment by crycode-de** [comment]
New option "enabled" is now available in v1.5.0 which can be installed via NPM know.
Tomorrow it will be in the latest repo and after some feedback I'll push it into stable.

Thank you for your report!
